spring:
  profiles:
    active: dev
flyway.baselineOnMigrate: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapping/*.xml
  typeAliasesPackage: com.org.account.po
